# ORIGINAL KEY FROM GITHUB.COM
#fitness=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

# Ashley's first groq key.
#fitness = "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"

# The new key is named "October_24_2024" online on the groq API Key page.
fitness = "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"
