# ORIGINAL KEY FROM GITHUB.COM
#fitness=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

# Ashwley's new key created on October 24, 2024 
fitness = "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"